import type { Metadata } from 'next'
import { M_PLUS_1 } from "next/font/google";
import { ThemeProvider } from 'next-themes'
import './globals.css'


const mPlus1 = M_PLUS_1({
  weight: ["400", "700", "900"], // 使用する太さを配列で指定
  style: ["normal"],
  subsets: ["latin"],
  display: "swap", // ここが大事
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=light_mode" />
      </head>
      <body className={mPlus1.className}>
        <ThemeProvider defaultTheme="system" enableSystem={true}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
